// config-example.yml
development: 
  store: example.shopify.com
  password: secret
  theme_id: "live"
  bucket_size: 40 // default from docs
  refill_rate: 2 // default
  ignore_files: 
    - "*.swp"
    - "*~"
    - "config/settings_data.json"